services:
  kitty_website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kitty_website
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8006:8000"
    command: >
      gunicorn  --bind 0.0.0.0:8000 
              --workers 3 
              --timeout 60 
              kitty_website.wsgi:application
    # python manage.py runserver 0.0.0.0:8000

